### ISSUE TITLE
Add cleanup for PR previews

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1692]
Part of https://github.com/Qiskit/documentation/issues/1043.

We should add a new workflow `pr-preview-cleanup.yml`. It will:

1. Use the GitHub CLI or API to query which PR numbers are still open. Prefer using the CLI if possible. The CLI should already be authenticated and installed for us
2. Determine which folders are in the `gh-pages` branch in the format `pr-x`, like `pr-80`. Don't worry about other folders
3. Delete any folders for PRs that are not actively open.
4. Push the changes to `gh-pages` branch
    - No need to check the deployment status. You only need to trigger the redeploy of the site. 

Starter code:

```yaml
name: PR preview cleanup
on:
  workflow_dispatch:
  branch: [main]

jobs:
  preview-cleanup:
    name: PR preview cleanup
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Qiskit'
```

You'll find `scripts/pr-previews/deploy.py` useful. It probably makes sense to add `pr-previews/cleanup.py`. It may be worth factoring out helper functions into `pr-previews/utils.py`. Also look at `.github/workflows/pr-preview.yml`.
