### ISSUE TITLE
[nb-tester]: Improve config

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#2401]
### Context

We currently organise all notebooks into categories based on how and when we can test them. To test functions notebooks, we're gonna need two types of patch:
1. Local simulator: This is what we currently use for notebooks that run small circuits. It runs locally and returns realistic results.
2. Test eagle: This runs on IBM Quantum and returns nonsense results. The functions notebooks introduce the need for this backend because functions only accept a backend _name_ (string) rather than a backend _object._

During CI, we want to be able to run some notebooks with the local sim and others with test-eagle. We also want to disable all patching in our fortnightly cron job, and skip some notebooks in all cases.

This issue aims to add this ability, but also to try and reign in some of the complexity of all these branching paths.

### Idea

The config file currently organizes notebooks into categories, maybe we can include the type of patch in the config file too? The new format would look something like this:

```toml
[group-name]
notebooks = [
  "path/to/notebook.ipynb"
]
patches = {\
  patch_a = { provider="qiskit-fake-provider" },\
  patch_b = { provider="qiskit-ibm-runtime", backend_name="test-eagle" }\
}
```

The CLI would then just take one patch-related arg: The type of patch to apply. For example, the following command would run all groups with their specification for "patch_a". Different groups of notebooks can have different definitions of `patch_a`.

```
--patch patch_a
```

If a notebook group does not have the specified patch, we skip that group. If the patch is an empty dict, we run the group without patching.

<details><summary>Example of what the Qiskit/documentation config would look like</summary>

```toml
[normal-test]
notebooks = ["..."]
patches = { ci = {}, hardware = {} }

[mock-local-sim]
notebooks = ["..."]
patches = {\
  ci = { provider="qiskit-fake-provider" },\
  hardware = {}\
}

[mock-test-eagle]
notebooks = ["..."]
patches = {\
  ci = { provider="qiskit-ibm-runtime", backend-name="test-eagle" },\
  hardware = {}\
}

[only-submit-jobs]
notebooks = ["..."]
patches = { hardware = {} }

[exclude]
notebooks = ["..."]
patches = {}
```

In CI, we'd pass the argument `--patch ci`. For our fortnightly cron job, we'd pass the arg `--patch hardware`.

</details>
